[book]
authors = ["Nicolas Racchi"]
language = "en"
src = "src"
title = "The MSG-RS Book"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
